name: CVE Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Anchore_Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build . --file Dockerfile --tag cluster-sample-app:latest
      - uses: anchore/scan-action@v3
        with:
          id: scan
          image: "cluster-sample-app:latest"
          acs-report-enable: true
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
